import Shell from '@/components/Shell'
import theme from '@/mantine-theme/theme'
import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import '@mantine/core/styles.css'
import { Rubik } from 'next/font/google'

const rubik = Rubik({
  subsets: ['latin'],
  display: 'swap',
})

const metadata = {
  title: 'WOS - Fathom Recordings',
  description: 'Generated by Next.js',
}

interface Props {
  children: React.ReactNode
}

function RootLayout({ children }: Props) {
  return (
    <html lang="en" className={rubik.className} data-mantine-color-scheme="dark">
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body>
        <MantineProvider theme={theme} forceColorScheme="dark">
          <Shell>{children}</Shell>
        </MantineProvider>
      </body>
    </html>
  )
}

export { metadata }
export default RootLayout
